Update models restcontrollers
Newton-OOP2-AAAI/web-shop pull request #7
Opened 2021-03-02 18:34 UTC by IsaLjungdahl

2021-03-02 18:49 UTC, Abdih10 commented on src/main/java/org/newton/webshop/restControllers/CartRestController.java
> -                    cart.setItems(newCart.getItems());
Behövde vi inte den här eller ?

2021-03-02 19:58 UTC, DoNotWorr requested changes
Det som Abdi hittade i CartRestController.java behöver ändras tillbaka

2021-03-02 19:58 UTC, DoNotWorr commented on src/main/java/org/newton/webshop/restControllers/CartRestController.java
> -                    cart.setItems(newCart.getItems());
Ja den här ska nog vara kvar

2021-03-03 10:21 UTC, DoNotWorr approved these changes

2021-03-03 10:23 UTC, andrkavr approved these changes

2021-03-03 10:23 UTC, andrkavr commented on src/main/java/org/newton/webshop/LoadDatabase.java
> +            Item item1 = new Item(cart1, prod1, 5, "M");
Ser bra ut.

2021-03-03 10:24 UTC, merged